### ISSUE TITLE
release 2.0.0

### ISSUE THREAD

**Issue by threeturn** [zealot128/ruby-letsencrypt-cli#25]
Hi, are you going to release this gem? :)

**Comment by mathieujobin** [comment]
That would be nice indeed ! 
thanks for the hint on using master for solving the incompatibility error I was getting

```
         1: from /usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/acme-cli-0.6.1/lib/letsencrypt/cli/acme_wrapper.rb:25:in `new'
/usr/local/rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0/gems/acme-client-2.0.7/lib/acme/client.rb:33:in `initialize': unknown keyword: endpoint (ArgumentError)
```

in relation with https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/23

use `gem 'acme-cli', git: 'https://github.com/zealot128/ruby-acme-cli/'`
until rubygems has the official release
